name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
         python-version: '3.9'
      
    - name: Install dependencies
      run: make init
      
    - name: Run setup
      run: make develop
      
    - run: pytest
